
server:
  port: 8096

spring:
  application:
    name: traceability
  datasource:
    url: jdbc:mysql://localhost:3306/traceability
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin1@localhost:8099/eureka/

appDescription: "Pragma Challenge"
appVersion: "1.0.0"

