
server:
  port: 8096

spring:
  application:
    name: traceability
  data:
    mongodb:
      uri: mongodb://localhost:27017/traceability

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin1@localhost:8099/eureka/

appDescription: "Pragma Challenge"
appVersion: "1.0.0"

