
server:
        port: 8097

spring:
        application:
                name: trazabilidad
        datasource:
                url: jdbc:mysql://localhost:3306/twilio
                username: root
                password: 123456

        jpa:
                hibernate:
                        ddl-auto: update
                show-sql: true

eureka:
        client:
                service-url:
                        defaultZone: http://admin:admin1@localhost:8099/eureka/

appDescription: "Pragma Challenge"
appVersion: "1.0.0"


