server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plazoleta
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Plazoleta"
appVersion: "1.0.0"
